### ISSUE TITLE
ImportError: No module named gobject

### ISSUE THREAD

**Issue by Sicness** [Skype4Py/Skype4Py#25]
Skype4py has dependency, but no info about that.

Traceback (most recent call last):
  File "./main.py", line 4, in <module>
    Skype = Skype4Py.Skype()
  File "/usr/local/lib/python2.7/dist-packages/Skype4Py/skype.py", line 250, in **init**
    self._Api = SkypeAPI(Options)
  File "/usr/local/lib/python2.7/dist-packages/Skype4Py/api/posix.py", line 35, in SkypeAPI
    from posix_dbus import SkypeAPI
  File "/usr/local/lib/python2.7/dist-packages/Skype4Py/api/posix_dbus.py", line 48, in <module>
    import gobject
ImportError: No module named gobject

**Comment by davsebamse** [comment]
Skype4py depends on python-gobject and python-dbus on posix systems

**Comment by miohtama** [comment]
@davsebamse: Great work! I'll buy you a beer if we meet on some day :)

**Comment by davsebamse** [comment]
@miohtama thanks :-)
