### ISSUE TITLE
skype4py doesnt play well with API from skype version skype-ubuntu-lucid_4.3.0.37-1_i386.deb

### ISSUE THREAD

**Issue by quorak** [Skype4Py/Skype4Py#34]
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "build/bdist.linux-x86_64/egg/Skype4Py/utils.py", line 225, in run
    handler(_self.args, *_self.kwargs)
  File "/home/skype/sevabot/sevabot/bot/bot.py", line 95, in handleMessages
    logger.debug("Incoming %s - %s - %s: %s" % (status, msg.Chat.FriendlyName,
  File "build/bdist.linux-x86_64/egg/Skype4Py/chat.py", line 245, in _GetFriendlyName
    return self._Property('FRIENDLYNAME')
  File "build/bdist.linux-x86_64/egg/Skype4Py/chat.py", line 33, in _Property
    return self._Owner._Property('CHAT', self.Name, PropName, Value, Cache)
  File "build/bdist.linux-x86_64/egg/Skype4Py/skype.py", line 296, in _Property
    value = self._DoCommand('GET %s' % jarg, jarg)
  File "build/bdist.linux-x86_64/egg/Skype4Py/skype.py", line 281, in _DoCommand
    raise SkypeError(int(errnum), errstr)
SkypeError: [Errno 105] Invalid chat name

**Comment by Goz3rr** [comment]
@pedro-teixeira tried that, it does indeed skip the login screen but will never actually go online for me :(

**Comment by pedro-teixeira** [comment]
@Goz3rr it's working fine for me. Funny thing is that the interface looks like 4.3 but when you go to about you see 4.2.

**Comment by phoenixza1** [comment]
I recently set up SevaBot and even gave a talk on how to do it and add your own python scripts, while being oblivious to the above problem. 

Thankfully, Microsoft seems to have shown mercy and still allows  us to create an old style P2P group chats, by using the /createmoderatedchat command (typed into any skype chat, it will create a new empty P2P group chat).

So with that command, I created a group, invited the bot and it works. It still works with users in the group who are not in it's contacts list and even groups created by users no in it's contacts list.

**Comment by Reiner030** [comment]
@phoenixza1 big thx for the Info ... It helps a lot for new skypbot supported chats ;)

**Comment by LoganBarnett** [comment]
@phoenixza1's answer worked for me as well. When typing the command it isn't obvious that it actually worked, be sure to check your Recent tab for an `Empty Group`.

**Comment by linjan** [comment]
Same here. It makes some problems with bots Sevabot and Levitan. **/createmoderatedchat** didn't work in Linux version of Skype.

**Comment by Reiner030** [comment]
yes... it works only for the newer clients on Windows and MacOS. 
The Linux Client is sadly too old for this command.

**Comment by pedro-teixeira** [comment]
My solution here was to migrate to Slack.

**Comment by linjan** [comment]
Slack is perfect, but not free.(

**Comment by miohtama** [comment]
Another alternative is Flowdock http://flowdock.com/

Not free either, but at least if you are paying to them you know it is less likely you are going to be screwed in long run.

**Comment by BeLove** [comment]
@pedro-teixeira thx, works perfect.

**Comment by Bonfire** [comment]
This issue is still present. Downloading the 4.2 version of Skype does not fix the issue.
Any new chatrooms (Those using the new cloud group chatrooms) have this issue. The older chatrooms do not.

Once again, the error printed to console when Sevabot attempts to get the "New chatroom" ID.

```

Exception in thread Skype4Py MessageStatus event scheduler:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "build/bdist.linux-x86_64/egg/Skype4Py/utils.py", line 225, in run
    handler(*self.args, **self.kwargs)
  File "/root/sevabot/sevabot/bot/bot.py", line 95, in handleMessages
    logger.debug("Incoming %s - %s - %s: %s" % (status, msg.Chat.FriendlyName,
  File "build/bdist.linux-x86_64/egg/Skype4Py/chat.py", line 245, in _GetFriendlyName
    return self._Property('FRIENDLYNAME')
  File "build/bdist.linux-x86_64/egg/Skype4Py/chat.py", line 33, in _Property
    return self._Owner._Property('CHAT', self.Name, PropName, Value, Cache)
  File "build/bdist.linux-x86_64/egg/Skype4Py/skype.py", line 296, in _Property
    value = self._DoCommand('GET %s' % jarg, jarg)
  File "build/bdist.linux-x86_64/egg/Skype4Py/skype.py", line 281, in _DoCommand
    raise SkypeError(int(errnum), errstr)
SkypeError: [Errno 105] Invalid chat name

```

The error above shows the issue in Sevabot, however the issue lies in Skype4py

**Comment by kAlmAcetA** [comment]
@adampiskorski thanks for workaround, still working

**Comment by shaiban** [comment]
@adampiskorski wow!  thanks! this is really working!

**Comment by a74nh** [comment]
For me /createmoderatedchat now creates a new style chat (with id starting with 19: )

According to  http://www.skaip.org/skype-chat-commands :
"Since May 22, 2016 on Skype is not possible to create P2P-chats. Nevertheless, cloud chat now also support moderating functions."

EDIT: I was still able to create a new p2p using the old 4.2 version of skype on Linux

**Comment by gmale** [comment]
Our sevabot instance (which, of course uses Skype4Py) just stopped working in the middle of the day today. Nothing has changed on our end but sevabot no longer recognizes any group chats. It seems like some fundamental change has been made behind the scenes to how these Skype groups work. We're still investigating a workaround . . .

. . .  it turns out that individual chats still work. So we're going to ask the team to transition to that for now (just message the bot directly instead of in the group chat) and look into moving to hubot. I have a feeling that some of the [newer hubot skype adapters](https://www.npmjs.com/package/hubot-skype-bot) will work because they don't rely on Skype4Py which uses [D-Bus ](https://dbus.freedesktop.org/doc/dbus-tutorial.html)and Skype seems to have changed how group chats interact with D-Bus.

**Comment by linjan** [comment]
@gmale, now (in real time) Skype force converting p2p group chats into cloud chats. Old version of skype (which used in linux) will not work in that chats. As a result, sevabot too.
