### ISSUE TITLE
Issue with unit tests. ImportError: No module named pkg_resources

### ISSUE THREAD

**Issue by chrissound** [Skype4Py/Skype4Py#38]
Hi there.

I'm getting the following error:
```
======================================================================
ERROR: testApiWrapperVersion (skypetest.SkypeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chris/temp/skype4py/unittests/skypetest.py", line 381, in testApiWrapperVersion
    t = self.obj.ApiWrapperVersion
  File "/home/chris/temp/skype4py/Skype4Py/skype.py", line 904, in _GetApiWrapperVersion
    import pkg_resources
ImportError: No module named pkg_resources

----------------------------------------------------------------------
Ran 411 tests in 0.392s

FAILED (errors=1)
```

Running Python 2.7.8.

I've run:
pip install --upgrade distribute
pip install --upgrade setuptools

Any idea as to what may be causing this?

**Comment by davsebamse** [comment]
In ubuntu you have to install the package python-pkg-resources
