### ISSUE TITLE
Getting Skype4Py.errors.SkypeError: [Errno 15] Unknown message

### ISSUE THREAD

**Issue by mayankraipure** [Skype4Py/Skype4Py#44]
Trying to run this 
print 'Sender Name:' , skype.Message().Sender.FullName

Traceback (most recent call last):
  File "/home/skype/sevabot/modules/prog.py", line 33, in <module>
    print 'Sender Name:' , skype.Message().Sender.FullName
  File "/usr/local/lib/python2.7/dist-packages/Skype4Py/skype.py", line 665, in Message
    o.Status # Test if such an id is known.
  File "/usr/local/lib/python2.7/dist-packages/Skype4Py/chat.py", line 573, in _GetStatus
    return str(self._Property('STATUS'))
  File "/usr/local/lib/python2.7/dist-packages/Skype4Py/chat.py", line 427, in _Property
    return self._Owner._Property('CHATMESSAGE', self.Id, PropName, Value, Cache)
  File "/usr/local/lib/python2.7/dist-packages/Skype4Py/skype.py", line 296, in _Property
    value = self._DoCommand('GET %s' % jarg, jarg)
  File "/usr/local/lib/python2.7/dist-packages/Skype4Py/skype.py", line 281, in _DoCommand
    raise SkypeError(int(errnum), errstr)
Skype4Py.errors.SkypeError: [Errno 15] Unknown message

**Comment by davsebamse** [comment]
What information are you looking for? The name that you send with, or whom send the message?

In the latter case can you use ```msg.FromDisplayName``` on the message instance you get when listing to the onMessageStatus event.
