### ISSUE TITLE
Still working, skypeforlinux ??

### ISSUE THREAD

**Issue by Erim32** [Skype4Py/Skype4Py#81]
Hi, great work,
Does  Skype4Py still working in 2017 ?  on Skypeforlinux ??

> Important notice: All Skype for Linux clients version 4.3 and older will be retired on July 1, 2017. To keep chatting, please install the latest version of Skype for Linux.

source: skype website

**Comment by olleharstedt** [comment]
I wonder this, too. When running the first example (display contact), the script throws

```bash
$ ./test1.py
Traceback (most recent call last):
  File "./test1.py", line 9, in <module>
    skype.Attach()
  File "/home/olle/kod/Skype4Py/Skype4Py/skype.py", line 408, in Attach
    self._Api.attach(self.Timeout, Wait)
  File "/home/olle/kod/Skype4Py/Skype4Py/api/posix_dbus.py", line 152, in attach
    raise SkypeAPIError('Skype attach timeout')
Skype4Py.errors.SkypeAPIError: Skype attach timeout
```

**Comment by coocla** [comment]
I have the same problem

**Comment by raowl** [comment]
me too, any light on this?

**Comment by nikswap** [comment]
Microsoft have discontinued the old skype api, with the old clients and introduced a new api. See https://dev.skype.com/ for how to use the api.
